version: "3"
services:
    app:
        build:
            context: .
            dockerfile: _docker/app/DockerFile
        volumes:
            - ./:/var/www/html
        ports:
            -   "8080:80"
        depends_on:
            - db
        container_name: project_app_yarik
        command: >
            sh -c
            "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache &&
             chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache &&
             apache2-foreground"
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: asd123
            MYSQL_DATABASE: blog-project
        ports:
            -   "3306:3306"
        volumes:
            -   ./tmp/db:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            -   "8090:80"
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_USER=root
            - DB_PASSWORD=asd123
        depends_on:
            -   db


